# Generated by Django 5.2.6 on 2025-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('Brand_Name', models.CharField(max_length=10)),
                ('Model_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=10)),
                ('Mfg_Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
